
import { Nunito } from 'next/font/google'
import "./globals.css";

const nunito = Nunito({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

import { Provider } from './context_login_notif';
import { FetchDataProvider } from './context_fecthData';

export const metadata = {
  title: "Timesheet Management",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={nunito.className}>
        <Provider>
          <FetchDataProvider>
            {children}
          </FetchDataProvider>
        </Provider>
      </body>
    </html>
  );
};


